services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_TICK_TIME: 500
    networks:
      - rede-distribuida

  # --- OS 3 MERCADOS ---
  mercado1:
    build: .
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
    ports:
      - "8081:8080"
    depends_on:
      - zookeeper
    networks:
      - rede-distribuida

  mercado2:
    build: .
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
    ports:
      - "8082:8080"
    depends_on:
      - zookeeper
    networks:
      - rede-distribuida

  mercado3:
    build: .
    environment:
      - ZOOKEEPER_HOST=zookeeper:2181
    ports:
      - "8083:8080"
    depends_on:
      - zookeeper
    networks:
      - rede-distribuida

  # ... (zookeeper e mercados continuam iguais) ...

  # --- SERVIDOR DO RESTAURANTE (RMI) ---
  restaurante-server:
    build: 
      context: .
      dockerfile: Dockerfile.client
    # AGORA O COMANDO É SÓ A CLASSE DO SERVIDOR
    command: ["br.edu.projeto.restaurante.server.Servidor"] 
    environment:
      - RMI_HOSTNAME=restaurante-server
    ports:
      - "3099:3099"
    networks:
      - rede-distribuida

  # --- CLIENTE DO RESTAURANTE (UI) ---
  restaurante-cliente:
    build: 
      context: .
      dockerfile: Dockerfile.client
    # AGORA O COMANDO É SÓ A CLASSE DO CLIENTE
    command: ["br.edu.projeto.restaurante.client.ClienteRestaurante"]
    environment:
      - SERVER_HOST=restaurante-server
      - ZOOKEEPER_HOST=zookeeper:2181
    stdin_open: true
    tty: true
    depends_on:
      - restaurante-server
      - mercado1
    networks:
      - rede-distribuida

networks:
  rede-distribuida:
    driver: bridge