# Define o nível padrão como INFO (Mostra suas mensagens importantes)
org.slf4j.simpleLogger.defaultLogLevel=info

# Define que mensagens do Zookeeper só aparecem se forem WARN ou ERRO
org.slf4j.simpleLogger.log.org.apache.zookeeper=warn

# Formato do log (opcional, para ficar mais limpo)
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false